In [115]:
import pandas as pd

df = pd.read_csv("data/garments_worker_productivity.csv")

print(df.head())
print(df.shape)
print(df.columns)

       date   quarter  department       day  team  targeted_productivity  \
0  1/1/2015  Quarter1      sweing  Thursday     8                   0.80
1  1/1/2015  Quarter1  finishing   Thursday     1                   0.75
2  1/1/2015  Quarter1      sweing  Thursday    11                   0.80
3  1/1/2015  Quarter1      sweing  Thursday    12                   0.80
4  1/1/2015  Quarter1      sweing  Thursday     6                   0.80

     smv     wip  over_time  incentive  idle_time  idle_men  \
0  26.16  1108.0       7080         98        0.0         0
1   3.94     NaN        960          0        0.0         0
2  11.41   968.0       3660         50        0.0         0
3  11.41   968.0       3660         50        0.0         0
4  25.90  1170.0       1920         50        0.0         0

   no_of_style_change  no_of_workers  actual_productivity
0                   0           59.0             0.940725
1                   0            8.0             0.886500
2                   0           30.5             0.800570
3                   0           30.5             0.800570
4                   0           56.0             0.800382
(1197, 15)
Index(['date', 'quarter', 'department', 'day', 'team', 'targeted_productivity',
       'smv', 'wip', 'over_time', 'incentive', 'idle_time', 'idle_men',
       'no_of_style_change', 'no_of_workers', 'actual_productivity'],
      dtype='str')

In [116]:
import pandas as pd

df = pd.read_csv("data/garments_worker_productivity.csv")

print(df.head())
print(df.shape)
print(df.columns)

       date   quarter  department       day  team  targeted_productivity  \
0  1/1/2015  Quarter1      sweing  Thursday     8                   0.80
1  1/1/2015  Quarter1  finishing   Thursday     1                   0.75
2  1/1/2015  Quarter1      sweing  Thursday    11                   0.80
3  1/1/2015  Quarter1      sweing  Thursday    12                   0.80
4  1/1/2015  Quarter1      sweing  Thursday     6                   0.80

     smv     wip  over_time  incentive  idle_time  idle_men  \
0  26.16  1108.0       7080         98        0.0         0
1   3.94     NaN        960          0        0.0         0
2  11.41   968.0       3660         50        0.0         0
3  11.41   968.0       3660         50        0.0         0
4  25.90  1170.0       1920         50        0.0         0

   no_of_style_change  no_of_workers  actual_productivity
0                   0           59.0             0.940725
1                   0            8.0             0.886500
2                   0           30.5             0.800570
3                   0           30.5             0.800570
4                   0           56.0             0.800382
(1197, 15)
Index(['date', 'quarter', 'department', 'day', 'team', 'targeted_productivity',
       'smv', 'wip', 'over_time', 'incentive', 'idle_time', 'idle_men',
       'no_of_style_change', 'no_of_workers', 'actual_productivity'],
      dtype='str')

In [117]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   1197 non-null   str
 1   quarter                1197 non-null   str
 2   department             1197 non-null   str
 3   day                    1197 non-null   str
 4   team                   1197 non-null   int64
 5   targeted_productivity  1197 non-null   float64
 6   smv                    1197 non-null   float64
 7   wip                    691 non-null    float64
 8   over_time              1197 non-null   int64
 9   incentive              1197 non-null   int64
 10  idle_time              1197 non-null   float64
 11  idle_men               1197 non-null   int64
 12  no_of_style_change     1197 non-null   int64
 13  no_of_workers          1197 non-null   float64
 14  actual_productivity    1197 non-null   float64
dtypes: float64(6), int64(5), str(4)
memory usage: 140.4 KB

In [118]:
df.isnull().sum()

date                       0
quarter                    0
department                 0
day                        0
team                       0
targeted_productivity      0
smv                        0
wip                      506
over_time                  0
incentive                  0
idle_time                  0
idle_men                   0
no_of_style_change         0
no_of_workers              0
actual_productivity        0
dtype: int64

In [119]:
df.describe()

,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
count,1197.000000,1197.000000,1197.000000,691.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000
mean,6.426901,0.729632,15.062172,1190.465991,4567.460317,38.210526,0.730159,0.369256,0.150376,34.609858,0.735091
std,3.463963,0.097891,10.943219,1837.455001,3348.823563,160.182643,12.709757,3.268987,0.427848,22.197687,0.174488
min,1.000000,0.070000,2.900000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.233705
25%,3.000000,0.700000,3.940000,774.500000,1440.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.650307
50%,6.000000,0.750000,15.260000,1039.000000,3960.000000,0.000000,0.000000,0.000000,0.000000,34.000000,0.773333
75%,9.000000,0.800000,24.260000,1252.500000,6960.000000,50.000000,0.000000,0.000000,0.000000,57.000000,0.850253
max,12.000000,0.800000,54.560000,23122.000000,25920.000000,3600.000000,300.000000,45.000000,2.000000,89.000000,1.120437

In [120]:
df["MeetsTarget"] = (
    df["actual_productivity"] >= df["targeted_productivity"]
).astype(int)

print(df["MeetsTarget"].value_counts())

MeetsTarget
1    875
0    322
Name: count, dtype: int64

In [121]:
df[[
    "targeted_productivity",
    "actual_productivity",
    "MeetsTarget"
]].head(10)

   targeted_productivity  actual_productivity  MeetsTarget
0                   0.80             0.940725            1
1                   0.75             0.886500            1
2                   0.80             0.800570            1
3                   0.80             0.800570            1
4                   0.80             0.800382            1
5                   0.80             0.800125            1
6                   0.75             0.755167            1
7                   0.75             0.753683            1
8                   0.75             0.753098            1
9                   0.75             0.750428            1

In [122]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   1197 non-null   str
 1   quarter                1197 non-null   str
 2   department             1197 non-null   str
 3   day                    1197 non-null   str
 4   team                   1197 non-null   int64
 5   targeted_productivity  1197 non-null   float64
 6   smv                    1197 non-null   float64
 7   wip                    691 non-null    float64
 8   over_time              1197 non-null   int64
 9   incentive              1197 non-null   int64
 10  idle_time              1197 non-null   float64
 11  idle_men               1197 non-null   int64
 12  no_of_style_change     1197 non-null   int64
 13  no_of_workers          1197 non-null   float64
 14  actual_productivity    1197 non-null   float64
 15  MeetsTarget            1197 non-null   int64
dtypes: float64(6), int64(6), str(4)
memory usage: 149.8 KB

In [123]:
df.isnull().sum()

date                       0
quarter                    0
department                 0
day                        0
team                       0
targeted_productivity      0
smv                        0
wip                      506
over_time                  0
incentive                  0
idle_time                  0
idle_men                   0
no_of_style_change         0
no_of_workers              0
actual_productivity        0
MeetsTarget                0
dtype: int64

In [124]:
from sklearn.model_selection import train_test_split

train_idx, test_idx = train_test_split(
    df.index,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(train_idx))
print("Testing samples:", len(test_idx))

Training samples: 957
Testing samples: 240

In [125]:
regression_features = [
    col for col in df.columns
    if col not in ["actual_productivity", "MeetsTarget"]
]

classification_features = [
    col for col in df.columns
    if col not in ["actual_productivity", "MeetsTarget"]
]

print("Features:")
print(regression_features)

Features:
['date', 'quarter', 'department', 'day', 'team', 'targeted_productivity', 'smv', 'wip', 'over_time', 'incentive', 'idle_time', 'idle_men', 'no_of_style_change', 'no_of_workers']

In [126]:
X_reg = df[regression_features]
y_reg = df["actual_productivity"]

X_cls = df[classification_features]
y_cls = df["MeetsTarget"]

print("Regression X shape:", X_reg.shape)
print("Regression y shape:", y_reg.shape)

print("Classification X shape:", X_cls.shape)
print("Classification y shape:", y_cls.shape)

Regression X shape: (1197, 14)
Regression y shape: (1197,)
Classification X shape: (1197, 14)
Classification y shape: (1197,)

In [127]:
categorical_features = X_reg.select_dtypes(
    include=["object"]
).columns.tolist()

numerical_features = X_reg.select_dtypes(
    exclude=["object"]
).columns.tolist()

print("Categorical features:")
print(categorical_features)

print("\nNumerical features:")
print(numerical_features)

Categorical features:
['date', 'quarter', 'department', 'day']

Numerical features:
['team', 'targeted_productivity', 'smv', 'wip', 'over_time', 'incentive', 'idle_time', 'idle_men', 'no_of_style_change', 'no_of_workers']

C:\Users\Yashish\AppData\Local\Temp\ipykernel_22692\1902109029.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X_reg.select_dtypes(

Creating the preprocessing pipeline

In [128]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [129]:
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [130]:
preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numerical_features),
    ("cat", categorical_transformer, categorical_features)
])

In [131]:
X_reg_train = X_reg.loc[train_idx]
X_reg_test = X_reg.loc[test_idx]

y_reg_train = y_reg.loc[train_idx]
y_reg_test = y_reg.loc[test_idx]

X_cls_train = X_cls.loc[train_idx]
X_cls_test = X_cls.loc[test_idx]

y_cls_train = y_cls.loc[train_idx]
y_cls_test = y_cls.loc[test_idx]

In [132]:
print("Categorical features:", categorical_features)
print("Numerical features:", numerical_features)

Categorical features: ['date', 'quarter', 'department', 'day']
Numerical features: ['team', 'targeted_productivity', 'smv', 'wip', 'over_time', 'incentive', 'idle_time', 'idle_men', 'no_of_style_change', 'no_of_workers']

Scikit-learn Linear Regression

In [133]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import time
import numpy as np

In [134]:
regression_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

In [135]:
start_time = time.perf_counter()

regression_model.fit(X_reg_train, y_reg_train)

regression_train_time = time.perf_counter() - start_time

print("Regression training time:", regression_train_time, "seconds")

Regression training time: 0.023655700002564117 seconds

In [136]:
start_time = time.perf_counter()

y_reg_pred = regression_model.predict(X_reg_test)

regression_prediction_time = time.perf_counter() - start_time

print("Regression prediction time:", regression_prediction_time, "seconds")

Regression prediction time: 0.010817000002134591 seconds

In [137]:
mae = mean_absolute_error(y_reg_test, y_reg_pred)

rmse = np.sqrt(
    mean_squared_error(y_reg_test, y_reg_pred)
)

r2 = r2_score(y_reg_test, y_reg_pred)

print("MAE :", mae)
print("RMSE:", rmse)
print("R2  :", r2)

MAE : 0.11209628468388427
RMSE: 0.15064514829331035
R2  : 0.14531628599830804

In [138]:
sklearn_regression_results = {
    "Model": "Scikit-learn Linear Regression",
    "MAE": mae,
    "RMSE": rmse,
    "R2": r2,
    "Training Time": regression_train_time,
    "Prediction Time": regression_prediction_time
}

print(sklearn_regression_results)

{'Model': 'Scikit-learn Linear Regression', 'MAE': 0.11209628468388427, 'RMSE': np.float64(0.15064514829331035), 'R2': 0.14531628599830804, 'Training Time': 0.023655700002564117, 'Prediction Time': 0.010817000002134591}

Scikit-learn Logistic Regression

In [139]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [140]:
classification_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=1000))
])

In [141]:
start_time = time.perf_counter()

classification_model.fit(X_cls_train, y_cls_train)

classification_train_time = time.perf_counter() - start_time

print("Classification training time:",
      classification_train_time, "seconds")

Classification training time: 0.03732329999911599 seconds

In [142]:
start_time = time.perf_counter()

y_cls_pred = classification_model.predict(X_cls_test)

classification_prediction_time = time.perf_counter() - start_time

print("Classification prediction time:",
      classification_prediction_time, "seconds")

Classification prediction time: 0.01106170000275597 seconds

In [143]:
accuracy = accuracy_score(y_cls_test, y_cls_pred)

precision = precision_score(y_cls_test, y_cls_pred, zero_division=0)

recall = recall_score(y_cls_test, y_cls_pred, zero_division=0)

f1 = f1_score(y_cls_test, y_cls_pred, zero_division=0)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1-score :", f1)

Accuracy : 0.75
Precision: 0.7746478873239436
Recall   : 0.9322033898305084
F1-score : 0.8461538461538461

In [144]:
sklearn_classification_results = {
    "Model": "Scikit-learn Logistic Regression",
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1": f1,
    "Training Time": classification_train_time,
    "Prediction Time": classification_prediction_time
}

print(sklearn_classification_results)

{'Model': 'Scikit-learn Logistic Regression', 'Accuracy': 0.75, 'Precision': 0.7746478873239436, 'Recall': 0.9322033898305084, 'F1': 0.8461538461538461, 'Training Time': 0.03732329999911599, 'Prediction Time': 0.01106170000275597}

In [145]:
sklearn_regression_table = pd.DataFrame([sklearn_regression_results])

sklearn_classification_table = pd.DataFrame([sklearn_classification_results])

print("Regression Results")
display(sklearn_regression_table)

print("\nClassification Results")
display(sklearn_classification_table)

Regression Results

,Model,MAE,RMSE,R2,Training Time,Prediction Time
0,Scikit-learn Linear Regression,0.112096,0.150645,0.145316,0.023656,0.010817

Classification Results

,Model,Accuracy,Precision,Recall,F1,Training Time,Prediction Time
0,Scikit-learn Logistic Regression,0.75,0.774648,0.932203,0.846154,0.037323,0.011062

In [146]:
import os

os.makedirs("results", exist_ok=True)

sklearn_regression_table.to_csv(
    "results/sklearn_regression_results.csv",
    index=False
)

sklearn_classification_table.to_csv(
    "results/sklearn_classification_results.csv",
    index=False
)

print("Scikit-learn results saved.")

Scikit-learn results saved.

PART B - FROM SCRATCH

In [147]:
import numpy as np
import pandas as pd
import time

In [148]:
# Part B setup

import numpy as np
import pandas as pd
import time

# Load the dataset again
df = pd.read_csv("data/garments_worker_productivity.csv")

# Create classification target
df["MeetsTarget"] = (
    df["actual_productivity"] >= df["targeted_productivity"]
).astype(int)

# Define features
regression_features = [
    col for col in df.columns
    if col not in ["actual_productivity", "MeetsTarget"]
]

classification_features = regression_features.copy()

# Identify categorical and numerical features
categorical_features = df[regression_features].select_dtypes(
    include=["object"]
).columns.tolist()

numerical_features = df[regression_features].select_dtypes(
    exclude=["object"]
).columns.tolist()

# Recreate the SAME 80/20 split using the same random seed.
# This is only for reproducing the fixed split;
# no sklearn train-test utility is used here.
rng = np.random.RandomState(42)
indices = np.arange(len(df))
rng.shuffle(indices)

test_size = int(np.ceil(len(df) * 0.2))

test_idx = indices[:test_size]
train_idx = indices[test_size:]

# Create manual copy
manual_df = df.copy()

manual_features = regression_features.copy()

manual_X = manual_df[manual_features].copy()

manual_y_reg = manual_df["actual_productivity"].copy()
manual_y_cls = manual_df["MeetsTarget"].copy()

print("Dataset shape:", df.shape)
print("Training samples:", len(train_idx))
print("Testing samples:", len(test_idx))
print("Categorical features:", categorical_features)
print("Numerical features:", numerical_features)

Dataset shape: (1197, 16)
Training samples: 957
Testing samples: 240
Categorical features: ['date', 'quarter', 'department', 'day']
Numerical features: ['team', 'targeted_productivity', 'smv', 'wip', 'over_time', 'incentive', 'idle_time', 'idle_men', 'no_of_style_change', 'no_of_workers']

C:\Users\Yashish\AppData\Local\Temp\ipykernel_22692\1504731254.py:24: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = df[regression_features].select_dtypes(

In [149]:
manual_X = pd.get_dummies(
    manual_X,
    columns=categorical_features,
    drop_first=False
)

manual_X = manual_X.astype(float)

print("Shape after encoding:", manual_X.shape)
print(manual_X.head())

Shape after encoding: (1197, 83)
   team  targeted_productivity    smv     wip  over_time  incentive  \
0   8.0                   0.80  26.16  1108.0     7080.0       98.0
1   1.0                   0.75   3.94     NaN      960.0        0.0
2  11.0                   0.80  11.41   968.0     3660.0       50.0
3  12.0                   0.80  11.41   968.0     3660.0       50.0
4   6.0                   0.80  25.90  1170.0     1920.0       50.0

   idle_time  idle_men  no_of_style_change  no_of_workers  ...  \
0        0.0       0.0                 0.0           59.0  ...
1        0.0       0.0                 0.0            8.0  ...
2        0.0       0.0                 0.0           30.5  ...
3        0.0       0.0                 0.0           30.5  ...
4        0.0       0.0                 0.0           56.0  ...

   quarter_Quarter5  department_finishing  department_finishing   \
0               0.0                   0.0                    0.0
1               0.0                   0.0                    1.0
2               0.0                   0.0                    0.0
3               0.0                   0.0                    0.0
4               0.0                   0.0                    0.0

   department_sweing  day_Monday  day_Saturday  day_Sunday  day_Thursday  \
0                1.0         0.0           0.0         0.0           1.0
1                0.0         0.0           0.0         0.0           1.0
2                1.0         0.0           0.0         0.0           1.0
3                1.0         0.0           0.0         0.0           1.0
4                1.0         0.0           0.0         0.0           1.0

   day_Tuesday  day_Wednesday
0          0.0            0.0
1          0.0            0.0
2          0.0            0.0
3          0.0            0.0
4          0.0            0.0

[5 rows x 83 columns]

In [150]:
manual_X_train = manual_X.iloc[train_idx].copy()
manual_X_test = manual_X.iloc[test_idx].copy()

y_train_reg_manual = manual_y_reg.iloc[train_idx].to_numpy()
y_test_reg_manual = manual_y_reg.iloc[test_idx].to_numpy()

y_train_cls_manual = manual_y_cls.iloc[train_idx].to_numpy()
y_test_cls_manual = manual_y_cls.iloc[test_idx].to_numpy()

print("Training shape:", manual_X_train.shape)
print("Testing shape:", manual_X_test.shape)

Training shape: (957, 83)
Testing shape: (240, 83)

In [151]:
for column in manual_X_train.columns:
    median_value = manual_X_train[column].median()

    manual_X_train[column] = manual_X_train[column].fillna(median_value)
    manual_X_test[column] = manual_X_test[column].fillna(median_value)

In [152]:
print("Missing values in training data:",
      manual_X_train.isnull().sum().sum())

print("Missing values in testing data:",
      manual_X_test.isnull().sum().sum())

Missing values in training data: 0
Missing values in testing data: 0

In [153]:
train_mean = manual_X_train.mean()
train_std = manual_X_train.std()

train_std = train_std.replace(0, 1)

In [154]:
manual_X_train_scaled = (
    manual_X_train - train_mean
) / train_std

manual_X_test_scaled = (
    manual_X_test - train_mean
) / train_std

In [155]:
X_train_manual = manual_X_train_scaled.to_numpy()
X_test_manual = manual_X_test_scaled.to_numpy()

In [156]:
print("Final training shape:", X_train_manual.shape)
print("Final testing shape:", X_test_manual.shape)

Final training shape: (957, 83)
Final testing shape: (240, 83)

Linear Regression from scratch

In [157]:
X_train_lr = np.c_[
    np.ones(X_train_manual.shape[0]),
    X_train_manual
]

X_test_lr = np.c_[
    np.ones(X_test_manual.shape[0]),
    X_test_manual
]

print("Training matrix:", X_train_lr.shape)
print("Testing matrix:", X_test_lr.shape)

Training matrix: (957, 84)
Testing matrix: (240, 84)

In [158]:
start_time = time.perf_counter()

linear_weights = np.linalg.lstsq(
    X_train_lr,
    y_train_reg_manual,
    rcond=None
)[0]

manual_regression_train_time = time.perf_counter() - start_time

print("Manual Linear Regression training time:",
      manual_regression_train_time,
      "seconds")

Manual Linear Regression training time: 0.006800100003601983 seconds

In [159]:
start_time = time.perf_counter()

y_reg_pred_manual = X_test_lr @ linear_weights

manual_regression_prediction_time = (
    time.perf_counter() - start_time
)

print("Manual Linear Regression prediction time:",
      manual_regression_prediction_time,
      "seconds")

Manual Linear Regression prediction time: 0.00016549999418202788 seconds

Implement the regression metrics ourselves

In [160]:
def manual_mae(y_true, y_pred):
    return np.mean(np.abs(y_true - y_pred))

In [161]:
def manual_rmse(y_true, y_pred):
    return np.sqrt(np.mean((y_true - y_pred) ** 2))

In [162]:
def manual_r2(y_true, y_pred):
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)

    return 1 - (ss_res / ss_tot)

In [163]:
manual_mae_value = manual_mae(
    y_test_reg_manual,
    y_reg_pred_manual
)

manual_rmse_value = manual_rmse(
    y_test_reg_manual,
    y_reg_pred_manual
)

manual_r2_value = manual_r2(
    y_test_reg_manual,
    y_reg_pred_manual
)

print("Manual MAE :", manual_mae_value)
print("Manual RMSE:", manual_rmse_value)
print("Manual R2  :", manual_r2_value)

Manual MAE : 0.11209630610472096
Manual RMSE: 0.1506450997886165
Manual R2  : 0.14531683637999204

In [164]:
manual_regression_results = {
    "Model": "From-Scratch Linear Regression",
    "MAE": manual_mae_value,
    "RMSE": manual_rmse_value,
    "R2": manual_r2_value,
    "Training Time": manual_regression_train_time,
    "Prediction Time": manual_regression_prediction_time
}

print(manual_regression_results)

{'Model': 'From-Scratch Linear Regression', 'MAE': np.float64(0.11209630610472096), 'RMSE': np.float64(0.1506450997886165), 'R2': np.float64(0.14531683637999204), 'Training Time': 0.006800100003601983, 'Prediction Time': 0.00016549999418202788}

In [165]:
X_train_log = np.c_[
    np.ones(X_train_manual.shape[0]),
    X_train_manual
]

X_test_log = np.c_[
    np.ones(X_test_manual.shape[0]),
    X_test_manual
]

print("Classification training shape:", X_train_log.shape)
print("Classification testing shape:", X_test_log.shape)

Classification training shape: (957, 84)
Classification testing shape: (240, 84)

In [166]:
def sigmoid(z):
    z = np.clip(z, -500, 500)
    return 1 / (1 + np.exp(-z))

In [167]:
def train_logistic_regression(X, y, learning_rate=0.01, epochs=2000):
    weights = np.zeros(X.shape[1])

    n_samples = X.shape[0]

    for epoch in range(epochs):

        # Linear combination
        z = X @ weights

        # Predicted probabilities
        probabilities = sigmoid(z)

        # Gradient
        gradient = (X.T @ (probabilities - y)) / n_samples

        # Update weights
        weights = weights - learning_rate * gradient

    return weights

In [168]:
start_time = time.perf_counter()

logistic_weights = train_logistic_regression(
    X_train_log,
    y_train_cls_manual,
    learning_rate=0.01,
    epochs=2000
)

manual_classification_train_time = (
    time.perf_counter() - start_time
)

print(
    "Manual Logistic Regression training time:",
    manual_classification_train_time,
    "seconds"
)

Manual Logistic Regression training time: 0.1346006999956444 seconds

In [169]:
start_time = time.perf_counter()

y_cls_prob_manual = sigmoid(
    X_test_log @ logistic_weights
)

manual_classification_prediction_time = (
    time.perf_counter() - start_time
)

print(
    "Manual Logistic Regression prediction time:",
    manual_classification_prediction_time,
    "seconds"
)

Manual Logistic Regression prediction time: 0.0002040999970631674 seconds

In [170]:
y_cls_pred_manual = (
    y_cls_prob_manual >= 0.5
).astype(int)

print(y_cls_pred_manual[:20])

[1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1]

Implement classification metrics manually

In [171]:
def confusion_values(y_true, y_pred):
    tp = np.sum((y_true == 1) & (y_pred == 1))
    tn = np.sum((y_true == 0) & (y_pred == 0))
    fp = np.sum((y_true == 0) & (y_pred == 1))
    fn = np.sum((y_true == 1) & (y_pred == 0))

    return tp, tn, fp, fn

In [172]:
def manual_accuracy(y_true, y_pred):
    tp, tn, fp, fn = confusion_values(y_true, y_pred)
    return (tp + tn) / (tp + tn + fp + fn)

In [173]:
def manual_precision(y_true, y_pred):
    tp, tn, fp, fn = confusion_values(y_true, y_pred)

    if tp + fp == 0:
        return 0

    return tp / (tp + fp)

In [174]:
def manual_recall(y_true, y_pred):
    tp, tn, fp, fn = confusion_values(y_true, y_pred)

    if tp + fn == 0:
        return 0

    return tp / (tp + fn)

In [175]:
def manual_f1(y_true, y_pred):
    precision = manual_precision(y_true, y_pred)
    recall = manual_recall(y_true, y_pred)

    if precision + recall == 0:
        return 0

    return 2 * (precision * recall) / (precision + recall)

Calculate the results

In [176]:
manual_accuracy_value = manual_accuracy(
    y_test_cls_manual,
    y_cls_pred_manual
)

manual_precision_value = manual_precision(
    y_test_cls_manual,
    y_cls_pred_manual
)

manual_recall_value = manual_recall(
    y_test_cls_manual,
    y_cls_pred_manual
)

manual_f1_value = manual_f1(
    y_test_cls_manual,
    y_cls_pred_manual
)

print("Accuracy :", manual_accuracy_value)
print("Precision:", manual_precision_value)
print("Recall   :", manual_recall_value)
print("F1-score :", manual_f1_value)

Accuracy : 0.725
Precision: 0.7605633802816901
Recall   : 0.9152542372881356
F1-score : 0.8307692307692307

In [177]:
manual_classification_results = {
    "Model": "From-Scratch Logistic Regression",
    "Accuracy": manual_accuracy_value,
    "Precision": manual_precision_value,
    "Recall": manual_recall_value,
    "F1": manual_f1_value,
    "Training Time": manual_classification_train_time,
    "Prediction Time": manual_classification_prediction_time
}

print(manual_classification_results)

{'Model': 'From-Scratch Logistic Regression', 'Accuracy': np.float64(0.725), 'Precision': np.float64(0.7605633802816901), 'Recall': np.float64(0.9152542372881356), 'F1': np.float64(0.8307692307692307), 'Training Time': 0.1346006999956444, 'Prediction Time': 0.0002040999970631674}

Create the comparison table

In [178]:
comparison_results = pd.DataFrame([
    sklearn_regression_results,
    manual_regression_results,
    sklearn_classification_results,
    manual_classification_results
])

display(comparison_results)

,Model,MAE,RMSE,R2,Training Time,Prediction Time,Accuracy,Precision,Recall,F1
0,Scikit-learn Linear Regression,0.112096,0.150645,0.145316,0.023656,0.010817,NaN,NaN,NaN,NaN
1,From-Scratch Linear Regression,0.112096,0.150645,0.145317,0.006800,0.000165,NaN,NaN,NaN,NaN
2,Scikit-learn Logistic Regression,NaN,NaN,NaN,0.037323,0.011062,0.750,0.774648,0.932203,0.846154
3,From-Scratch Logistic Regression,NaN,NaN,NaN,0.134601,0.000204,0.725,0.760563,0.915254,0.830769

In [179]:
comparison_results.to_csv(
    "results/full_comparison.csv",
    index=False
)

print("Comparison table saved successfully.")

Comparison table saved successfully.

In [180]:
classification_comparison = pd.DataFrame([
    sklearn_classification_results,
    manual_classification_results
])

display(classification_comparison)

,Model,Accuracy,Precision,Recall,F1,Training Time,Prediction Time
0,Scikit-learn Logistic Regression,0.750,0.774648,0.932203,0.846154,0.037323,0.011062
1,From-Scratch Logistic Regression,0.725,0.760563,0.915254,0.830769,0.134601,0.000204

Optimization

In [181]:
learning_rates = [0.001, 0.01, 0.05, 0.1]
epochs_list = [1000, 2000, 5000]

optimization_results = []

for lr in learning_rates:
    for epochs in epochs_list:

        start_time = time.perf_counter()

        weights = train_logistic_regression(
            X_train_log,
            y_train_cls_manual,
            learning_rate=lr,
            epochs=epochs
        )

        training_time = time.perf_counter() - start_time

        probabilities = sigmoid(X_test_log @ weights)

        predictions = (probabilities >= 0.5).astype(int)

        accuracy_value = manual_accuracy(
            y_test_cls_manual,
            predictions
        )

        precision_value = manual_precision(
            y_test_cls_manual,
            predictions
        )

        recall_value = manual_recall(
            y_test_cls_manual,
            predictions
        )

        f1_value = manual_f1(
            y_test_cls_manual,
            predictions
        )

        optimization_results.append({
            "Learning Rate": lr,
            "Epochs": epochs,
            "Accuracy": accuracy_value,
            "Precision": precision_value,
            "Recall": recall_value,
            "F1": f1_value,
            "Training Time": training_time
        })

optimization_df = pd.DataFrame(optimization_results)

display(optimization_df)

,Learning Rate,Epochs,Accuracy,Precision,Recall,F1,Training Time
0,0.001,1000,0.679167,0.804878,0.745763,0.774194,0.050884
1,0.001,2000,0.683333,0.779006,0.796610,0.787709,0.100074
2,0.001,5000,0.720833,0.769608,0.887006,0.824147,0.245433
3,0.010,1000,0.729167,0.766667,0.909605,0.832041,0.053500
4,0.010,2000,0.725000,0.760563,0.915254,0.830769,0.128352
5,0.010,5000,0.741667,0.775120,0.915254,0.839378,0.267993
6,0.050,1000,0.741667,0.775120,0.915254,0.839378,0.061615
7,0.050,2000,0.741667,0.780488,0.903955,0.837696,0.172712
8,0.050,5000,0.737500,0.779412,0.898305,0.834646,0.415339
9,0.100,1000,0.741667,0.780488,0.903955,0.837696,0.080800
10,0.100,2000,0.737500,0.776699,0.903955,0.835509,0.131380
11,0.100,5000,0.741667,0.780488,0.903955,0.837696,0.458307

In [182]:
optimized_learning_rate = 0.05
optimized_epochs = 1000

start_time = time.perf_counter()

optimized_weights = train_logistic_regression(
    X_train_log,
    y_train_cls_manual,
    learning_rate=optimized_learning_rate,
    epochs=optimized_epochs
)

optimized_training_time = time.perf_counter() - start_time

# Prediction
start_time = time.perf_counter()

optimized_probabilities = sigmoid(
    X_test_log @ optimized_weights
)

optimized_predictions = (
    optimized_probabilities >= 0.5
).astype(int)

optimized_prediction_time = time.perf_counter() - start_time

print("Optimized training time:", optimized_training_time)
print("Optimized prediction time:", optimized_prediction_time)

Optimized training time: 0.0696036000008462
Optimized prediction time: 0.00018390000332146883

In [183]:
optimized_accuracy = manual_accuracy(
    y_test_cls_manual,
    optimized_predictions
)

optimized_precision = manual_precision(
    y_test_cls_manual,
    optimized_predictions
)

optimized_recall = manual_recall(
    y_test_cls_manual,
    optimized_predictions
)

optimized_f1 = manual_f1(
    y_test_cls_manual,
    optimized_predictions
)

print("Optimized Accuracy :", optimized_accuracy)
print("Optimized Precision:", optimized_precision)
print("Optimized Recall   :", optimized_recall)
print("Optimized F1       :", optimized_f1)

Optimized Accuracy : 0.7416666666666667
Optimized Precision: 0.7751196172248804
Optimized Recall   : 0.9152542372881356
Optimized F1       : 0.8393782383419689

In [184]:
optimized_classification_results = {
    "Model": "Optimized From-Scratch Logistic Regression",
    "Accuracy": optimized_accuracy,
    "Precision": optimized_precision,
    "Recall": optimized_recall,
    "F1": optimized_f1,
    "Training Time": optimized_training_time,
    "Prediction Time": optimized_prediction_time,
    "Learning Rate": optimized_learning_rate,
    "Epochs": optimized_epochs
}

print(optimized_classification_results)

{'Model': 'Optimized From-Scratch Logistic Regression', 'Accuracy': np.float64(0.7416666666666667), 'Precision': np.float64(0.7751196172248804), 'Recall': np.float64(0.9152542372881356), 'F1': np.float64(0.8393782383419689), 'Training Time': 0.0696036000008462, 'Prediction Time': 0.00018390000332146883, 'Learning Rate': 0.05, 'Epochs': 1000}

In [185]:
optimization_df.to_csv(
    "results/logistic_optimization_results.csv",
    index=False
)

print("Optimization results saved.")

Optimization results saved.

In [186]:
final_comparison = pd.DataFrame([
    {
        "Model": sklearn_regression_results["Model"],
        "Task": "Regression",
        "MAE": sklearn_regression_results["MAE"],
        "RMSE": sklearn_regression_results["RMSE"],
        "R2": sklearn_regression_results["R2"],
        "Accuracy": np.nan,
        "Precision": np.nan,
        "Recall": np.nan,
        "F1": np.nan,
        "Training Time": sklearn_regression_results["Training Time"],
        "Prediction Time": sklearn_regression_results["Prediction Time"]
    },
    {
        "Model": manual_regression_results["Model"],
        "Task": "Regression",
        "MAE": manual_regression_results["MAE"],
        "RMSE": manual_regression_results["RMSE"],
        "R2": manual_regression_results["R2"],
        "Accuracy": np.nan,
        "Precision": np.nan,
        "Recall": np.nan,
        "F1": np.nan,
        "Training Time": manual_regression_results["Training Time"],
        "Prediction Time": manual_regression_results["Prediction Time"]
    },
    {
        "Model": sklearn_classification_results["Model"],
        "Task": "Classification",
        "MAE": np.nan,
        "RMSE": np.nan,
        "R2": np.nan,
        "Accuracy": sklearn_classification_results["Accuracy"],
        "Precision": sklearn_classification_results["Precision"],
        "Recall": sklearn_classification_results["Recall"],
        "F1": sklearn_classification_results["F1"],
        "Training Time": sklearn_classification_results["Training Time"],
        "Prediction Time": sklearn_classification_results["Prediction Time"]
    },
    {
        "Model": manual_classification_results["Model"],
        "Task": "Classification",
        "MAE": np.nan,
        "RMSE": np.nan,
        "R2": np.nan,
        "Accuracy": manual_classification_results["Accuracy"],
        "Precision": manual_classification_results["Precision"],
        "Recall": manual_classification_results["Recall"],
        "F1": manual_classification_results["F1"],
        "Training Time": manual_classification_results["Training Time"],
        "Prediction Time": manual_classification_results["Prediction Time"]
    },
    {
        "Model": optimized_classification_results["Model"],
        "Task": "Classification",
        "MAE": np.nan,
        "RMSE": np.nan,
        "R2": np.nan,
        "Accuracy": optimized_classification_results["Accuracy"],
        "Precision": optimized_classification_results["Precision"],
        "Recall": optimized_classification_results["Recall"],
        "F1": optimized_classification_results["F1"],
        "Training Time": optimized_classification_results["Training Time"],
        "Prediction Time": optimized_classification_results["Prediction Time"]
    }
])

display(final_comparison)

,Model,Task,MAE,RMSE,R2,Accuracy,Precision,Recall,F1,Training Time,Prediction Time
0,Scikit-learn Linear Regression,Regression,0.112096,0.150645,0.145316,NaN,NaN,NaN,NaN,0.023656,0.010817
1,From-Scratch Linear Regression,Regression,0.112096,0.150645,0.145317,NaN,NaN,NaN,NaN,0.006800,0.000165
2,Scikit-learn Logistic Regression,Classification,NaN,NaN,NaN,0.750000,0.774648,0.932203,0.846154,0.037323,0.011062
3,From-Scratch Logistic Regression,Classification,NaN,NaN,NaN,0.725000,0.760563,0.915254,0.830769,0.134601,0.000204
4,Optimized From-Scratch Logistic Regression,Classification,NaN,NaN,NaN,0.741667,0.775120,0.915254,0.839378,0.069604,0.000184

In [187]:
final_comparison.to_csv(
    "results/final_comparison.csv",
    index=False
)

print("Final comparison saved successfully.")

Final comparison saved successfully.

In [188]:
pd.DataFrame([optimized_classification_results]).to_csv(
    "results/optimized_logistic_regression.csv",
    index=False
)

print("Optimized model results saved.")

Optimized model results saved.

In [189]:
display(final_comparison)

,Model,Task,MAE,RMSE,R2,Accuracy,Precision,Recall,F1,Training Time,Prediction Time
0,Scikit-learn Linear Regression,Regression,0.112096,0.150645,0.145316,NaN,NaN,NaN,NaN,0.023656,0.010817
1,From-Scratch Linear Regression,Regression,0.112096,0.150645,0.145317,NaN,NaN,NaN,NaN,0.006800,0.000165
2,Scikit-learn Logistic Regression,Classification,NaN,NaN,NaN,0.750000,0.774648,0.932203,0.846154,0.037323,0.011062
3,From-Scratch Logistic Regression,Classification,NaN,NaN,NaN,0.725000,0.760563,0.915254,0.830769,0.134601,0.000204
4,Optimized From-Scratch Logistic Regression,Classification,NaN,NaN,NaN,0.741667,0.775120,0.915254,0.839378,0.069604,0.000184

In [190]:
optimization_df.to_csv(
    "results/logistic_optimization_results.csv",
    index=False
)

print("Optimization results saved.")

Optimization results saved.